// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DocScanFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCk3lszcWggFTF8_VlWS59YtcvHpsfirc4',
    appId: '1:845120022236:android:3492d1affa418dcc2cf619',
    messagingSenderId: '845120022236',
    projectId: 'tavilidocscan',
    storageBucket: 'tavilidocscan.firebasestorage.app',
  );

  /// iOS app for project [tavilidocscan] (from TaviliDocScan GoogleService-Info.plist).
  /// Bundle in Firebase console: scanner.tavili.com — FoodStock dev uses net.dev.tavili
  /// with a named secondary Firebase app initialized from these options.
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiDIgLmBknIzv_CuFis79mTPYMEkqotbQ',
    appId: '1:845120022236:ios:126caded22a388412cf619',
    messagingSenderId: '845120022236',
    projectId: 'tavilidocscan',
    storageBucket: 'tavilidocscan.firebasestorage.app',
    iosBundleId: 'net.dev.tavili',
  );
}
