include: package:flutter_lints/flutter.yaml

analyzer:
   strong-mode:
      implicit-casts: false
   language:
      strict-casts: false
   errors:
      always_declare_return_types : error
      avoid_empty_else : error
      camel_case_types : error
      avoid_slow_async_io : error
      avoid_types_as_parameter_names : error
      unrelated_type_equality_checks : error
      avoid_unnecessary_containers : error
      ambiguous_import: error
      unsafe_html: error
      avoid_print: error
      camel_case_extensions : error
      avoid_void_async : error
      cascade_invocations : error
      file_names : error
      sized_box_for_whitespace : error
      unawaited_futures : error
      unnecessary_await_in_return : error

      unnecessary_new : error


      missing_required_param: warning
      missing_return: warning
      prefer_relative_imports: ignore
      lines_longer_than_80_chars: ignore
      sort_pub_dependencies: ignore
      public_member_api_docs: ignore
      always_use_package_imports: ignore