part of 'more_details_bloc.dart';

@freezed
class MoreDetailsState with _$MoreDetailsState {
  const factory MoreDetailsState({
    required String selectCity,
    required bool isUpdate,
    required List<String> cityList,
    required List<String> filterList,
    required TextEditingController addressController,
    required TextEditingController emailController,
    required TextEditingController faxController,
    required TextEditingController cityController,
    required TextEditingController deviceTypeController,
    required TextEditingController otpController,
    required TextEditingController versionController,
    required File image,
    required bool isLoading,
    required bool isUpdating,
    required bool isShimmering,
    required CityListResModel? cityListResModel,
    required String companyLogo,
    required bool isFileSizeExceeds,
    required bool isUploadProcess,
    required String language,
    required String deviceType,
    required String version,
    required String OtpString,
  }) = _MoreDetailsState;

  factory MoreDetailsState.initial() => MoreDetailsState(
    selectCity: '',
        cityList: [],
        isUpdate: false,
        addressController: TextEditingController(),
        emailController: TextEditingController(),
        faxController: TextEditingController(),
        deviceTypeController:TextEditingController() ,
        otpController: TextEditingController(),
        versionController: TextEditingController(),
        image: File(''),
        isLoading: false,
        isUpdating: false,
        cityController: TextEditingController(),
        filterList: [],
        cityListResModel: CityListResModel(),
        companyLogo: '',
        isFileSizeExceeds: false,
        isShimmering: false,
        isUploadProcess: false,
    language: 'he',
    deviceType: '',
    OtpString: '',
    version: '',
      );
}
