part of 'store_bloc.dart';

@freezed
class StoreState with _$StoreState {
  const factory StoreState({
    required bool isCategoryExpand,
    required List<Category> productCategoryList,
    required List<ProductSale> productSalesList,
    required List<RecommendationData> recommendedProductsList,
    required List<PreviousOrderProductData> previousOrderProductsList,
    required SuppliersResModel suppliersList,
    required List<Brand> companiesList,
    required List<SearchModel> searchList,
    required bool isShimmering,
    required bool isLoading,
    required bool isProductLoading,
    required List<Product> productDetails,
    required List<ProductStockModel> productStockList,
    required int productStockUpdateIndex,
    required bool isSelectSupplier,
    required List<ProductSupplierModel> productSupplierList,
    required bool isCartCountChange,
    required String search,
    required bool isSearching,
    required int imageIndex,
    required TextEditingController searchController,
    required TextEditingController noteController,
    required RefreshController refreshController,
    required bool isCatVisible,
    required bool isSupplierVisible,
    required bool isCompanyVisible,
    required bool isGuestUser,
    required List<RelatedProductDatum> relatedProductList,
    required bool isRelatedShimmering,
    required bool showPesachBanner,
    required String pesachBannerURL,
    required double bottlePrice,
    required bool isSubUserAddToBasket,
    required bool isAccountPermissionShimmering,
    required bool pesachBannerShimmering,
    required bool isIncludedVat,
    required bool isSaleOn,
    required bool isAppOnMaintenance,
    required String language,
    required bool isDialogOpen,
    required bool retryLoading
  }) = _StoreState;

  factory StoreState.initial() => StoreState(
    isCategoryExpand: false,
        productCategoryList: [],
        productSalesList: [],
        recommendedProductsList: [],
        previousOrderProductsList: [],
        suppliersList: SuppliersResModel(),
        companiesList: [],
        searchList: [],
        isShimmering: false,
        isLoading: false,
        isProductLoading: false,
        productDetails: [],
        productStockUpdateIndex: -1,
        productStockList: [ProductStockModel(productId: '')],
        isSelectSupplier: false,
        productSupplierList: [],
        isCartCountChange: false,
        search: '',
        isSearching: false,
        imageIndex: 0,
        searchController: TextEditingController(),
        noteController: TextEditingController(),
        refreshController: RefreshController(),
        isCompanyVisible: true,
        isCatVisible: true,
        isSupplierVisible: true,
        isGuestUser: false,
    relatedProductList: [],
    isRelatedShimmering: false,
      pesachBannerURL: '',
      showPesachBanner: false,
      bottlePrice:0.0,
    isSubUserAddToBasket: false,
      isAccountPermissionShimmering : false,
    pesachBannerShimmering: false,
      isIncludedVat : false,
      isSaleOn : false,
      isAppOnMaintenance  : false,
       language:AppStrings.hebrewString,
      isDialogOpen:false,
      retryLoading:false
    
    
      );
}
