part of 'supplier_list_products_bloc.dart';

@freezed
class SupplierListProductsState with _$SupplierListProductsState {
  const factory SupplierListProductsState({
    required String supplierId,
    required String search,
    required List<BrandData> brandList,
    required List<SupplierCategoryData> supplierCategoryList,
    required List<ProductData> productList,
    required bool isShimmering,
    required bool isLoading,
    required bool isProductLoading,
    required List<Product> productDetails,
    required List<List<ProductStockModel>> productStockList,
    required int productStockUpdateIndex,
    required int pageNum,
    required bool isLoadMore,
    required bool isBottomOfProducts,
    required bool isSelectSupplier,
    required List<ProductSupplierModel> productSupplierList,
    required int imageIndex,
    required TextEditingController noteController,
    required RefreshController refreshController,
    required String searchType,
    required bool isGuestUser,
    required bool isGridView,
    required bool isCategoryExpand,
    required bool isSearching,
    required TextEditingController searchController,
    required List<SearchModel> searchList,
    required List<Category> productCategoryList,
    required bool isCatVisible,
    required List<RelatedProductDatum> relatedProductList,
    required bool isRelatedShimmering,
    required int productListIndex,
    required String searchArg,
    required double bottleDeposit,
    required bool isSubUserAddToBasket,
    required bool isIncludedVat,
    required bool isSaleOn,
    required bool isProgress,
    required String language,
    required bool isCartCountChange,
    required int cartCount,
    required int messageCount,
    required String? clubAgentId,
    String? selectedBrandId,
    required bool duringCelebration,
    required double bottlePrice,
    required bool isDeliveryScheduleLoading,
    required List<SupplierCityDeliveryDay> deliveryScheduleDays,
    String? deliveryScheduleCityName,
  }) = _SupplierListProductsState;

  factory SupplierListProductsState.initial() => SupplierListProductsState(
        supplierId: '',
        search: '',
        productList: [],
        brandList: [],
        supplierCategoryList: [],
        isShimmering: false,
        isLoading: false,
        isProductLoading: false,
        productDetails: [],
        productStockUpdateIndex: -1,
        productStockList: [
          [const ProductStockModel(productId: '')],
          [],
          []
        ],
        pageNum: 0,
        isLoadMore: false,
        isBottomOfProducts: false,
        isSelectSupplier: false,
        productSupplierList: [],
        imageIndex: 0,
        noteController: TextEditingController(),
        refreshController: RefreshController(),
        searchType: '',
        isGuestUser: false,
        isGridView: false,
        isCategoryExpand: false,
        isSearching: false,
        searchController: TextEditingController(),
        searchList: [],
        productCategoryList: [],
        isCatVisible: false,
        relatedProductList: [],
        isRelatedShimmering: false,
        productListIndex: 0,
        searchArg: '',
        bottleDeposit: 0,
        isSubUserAddToBasket: false,
        isIncludedVat: false,
        isSaleOn: false,
        isProgress: false,
        language: AppStrings.hebrewString,
        isCartCountChange: false,
        cartCount: 0,
        messageCount: 0,
        clubAgentId: '',
        selectedBrandId: '',
        duringCelebration: false,
        bottlePrice: 0.0,
        isDeliveryScheduleLoading: false,
        deliveryScheduleDays: [],
        deliveryScheduleCityName: null,
      );
}
