part of 'product_details_bloc.dart';

@freezed
class ProductDetailsState with _$ProductDetailsState {
  const factory ProductDetailsState({
    required bool isProductProblem,
    required bool isRefresh,
    required int selectedRadioTile,
    required List<int> productListIndex,
    required int productWeight,
    required String phoneNumber,
    required OrdersBySupplier orderBySupplierProduct,
    required OrderDatum orderData,
    required bool isShimmering,
    required bool isLoading,
    required int quantity,
    required int radioItemQuantity,
    required bool isAllCheck,
    required int missingQuantity,
    required String note,
    required TextEditingController addNoteController,
    required bool isRemoveProcess,
    required String language,
    required List<ProductStockModel> productStockList,
    required int productStockUpdateIndex,
    required bool isDuplicateOrderProcess,
    required bool isCartCount,
    required bool isSubUserCreateDuplicateOrder,
    required bool isIncludedVat,
    required File proofFile,
    required File proofFile1,
    required File proofFile2,
    required List<String> proofImagesList,
    required File driverDeliveryProofFile,
    required File driverDeliveryProofFile1,
    required File driverDeliveryProofFile2,
    required List<String> driverDeliveryProofImagesList,
    required GetReturnByIdResModel returnList,
    required Map<int, int> quantitiesPerRadio,
    required Map<int, Map<String, dynamic>> productIssueData,
    required String? userId,
    required List<StatusData> statusList,
    required String? reason,
    required int? unit,
    required bool? hasReturnProducts,
    required bool? shouldScrollToProofImages,
  }) = _ProductDetailsState;

  factory ProductDetailsState.initial() => ProductDetailsState(
      isProductProblem: false,
      isRefresh: false,
      selectedRadioTile: 0,
      productListIndex: [],
      productWeight: 0,
      phoneNumber: '',
      orderBySupplierProduct: const OrdersBySupplier(),
      orderData: const OrderDatum(),
      isShimmering: false,
      isLoading: false,
      quantity: 0,
      radioItemQuantity: 1,
      isAllCheck: false,
      missingQuantity: 0,
      note: '',
      addNoteController: TextEditingController(),
      isRemoveProcess: false,
      language: 'en',
      productStockList: [],
      productStockUpdateIndex: 0,
      isDuplicateOrderProcess: false,
      isCartCount: false,
      isSubUserCreateDuplicateOrder: false,
      isIncludedVat: false,
      proofFile: File(''),
      proofFile1: File(''),
      proofFile2: File(''),
      proofImagesList: [],
      driverDeliveryProofFile: File(''),
      driverDeliveryProofFile1: File(''),
      driverDeliveryProofFile2: File(''),
      driverDeliveryProofImagesList: [],
      returnList: GetReturnByIdResModel(),
      quantitiesPerRadio: {},
      productIssueData: {},
      userId: '',
      statusList: <StatusData>[],
      reason: '',
      unit: 0,
      hasReturnProducts: false,
      shouldScrollToProofImages: false);
}
