part of 'home_bloc.dart';

@freezed
class HomeState with _$HomeState {
  const factory HomeState({
    required String userImageUrl,
    required String userCompanyLogoUrl,
    required int cartCount,
    required int messageCount,
    required List<ProductSale> productSalesList,
    required bool isProductSaleShimmering,
    required bool isLoading,
    required bool isProductLoading,
    required bool allShimmering,
    required List<Product> productDetails,
    required List<List<ProductStockModel>> productStockList,
    required int productStockUpdateIndex,
    required bool isSelectSupplier,
    required List<ProductSupplierModel> productSupplierList,
    required bool isCartCountChange,
    required double totalCredit,
    required double thisMonthExpense,
    required double lastMonthExpense,
    required int orderThisMonth,
    required double balance,
    required int imageIndex,
    required List<MessageData> messageList,
    required bool isMessageShimmering,
    required double expensePercentage,
    required TextEditingController noteController,
    required List<RecommendationData> recommendedProductsList,
    required bool isShimmering,
    required bool isCategoryExpand,
    required bool isSearching,
    required TextEditingController searchController,
    required List<SearchModel> searchList,
    required String search,
    required List<Category> productCategoryList,
    required bool isCatVisible,
    required bool isGuestUser,
    required bool isRelatedShimmering,
    required List<RelatedProductDatum> relatedProductList,
    required int productListIndex,
    required bool showPesachBanner,
    required String pesachBannerURL,
    required bool pesachBannerShimmering,
    required double bottlePrice,
    required bool isSubUserAddToBasket,
    required bool isSubUserSeeWallet,
    required bool isAccountPermissionShimmering,
    required bool isIncludedVat,
    required bool isSaleOn,
    required bool isAppOnMaintenance,
    required String language,
    required bool isDialogOpen,
    required bool retryLoading,
    required BuildContext? context,
    required RefreshController refreshController,
    required bool isDialog,
    required bool showClientDataOnApp,
    required String? buttonEnglishText,
    required String? buttonHebrewText,
    required bool? allowOrdersWithoutMinimum,
    required int? noMinimumOrderHours,
    required String? lastOrderAboveMinimumAt,
    required String? lastOrderAboveMinimumText,
    required String? noMinimumDialogEventKey,
    required String? clubAgentId,
    required List<SupplierCustomerDetails> supplierCustomerDetails,
    required List<SupplierListData> suppliersDataList,
  }) = _HomeState;

  factory HomeState.initial() => HomeState(
        userImageUrl: '',
        userCompanyLogoUrl: '',
        cartCount: 0,
        messageCount: 0,
        productSalesList: [],
        isProductSaleShimmering: true,
        isLoading: false,
        isProductLoading: false,
        productDetails: [],
        productStockUpdateIndex: -1,
        productStockList: [
          [const ProductStockModel(productId: '')],
          [],
          [],
          [],
        ],
        isSelectSupplier: false,
        productSupplierList: [],
        isCartCountChange: false,
        balance: 0,
        lastMonthExpense: 0,
        orderThisMonth: 0,
        thisMonthExpense: 0,
        totalCredit: 0,
        imageIndex: 0,
        messageList: [],
        isMessageShimmering: false,
        expensePercentage: 0,
        bottlePrice: 0.0,
        noteController: TextEditingController(),
        recommendedProductsList: [],
        isShimmering: false,
        isCategoryExpand: false,
        isSearching: false,
        searchController: TextEditingController(),
        searchList: [],
        search: '',
        productCategoryList: [],
        isCatVisible: false,
        isGuestUser: false,
        isRelatedShimmering: false,
        relatedProductList: [],
        productListIndex: -1,
        pesachBannerURL: '',
        showPesachBanner: false,
        pesachBannerShimmering: false,
        isSubUserAddToBasket: false,
        isSubUserSeeWallet: false,
        isAccountPermissionShimmering: false,
        isIncludedVat: false,
        isSaleOn: false,
        isAppOnMaintenance: false,
        isDialogOpen: false,
        language: AppStrings.hebrewString,
        retryLoading: false,
        allShimmering: true,
        context: null,
        refreshController: RefreshController(),
        isDialog: false,
        showClientDataOnApp: false,
        buttonEnglishText: '',
        buttonHebrewText: '',
        allowOrdersWithoutMinimum: false,
        noMinimumOrderHours: 0,
        lastOrderAboveMinimumAt: '',
        lastOrderAboveMinimumText: '',
        noMinimumDialogEventKey: '',
        clubAgentId: '',
        supplierCustomerDetails: [],
        suppliersDataList: [],
      );
}
