part of 'recommendation_products_bloc.dart';

@freezed
class RecommendationProductsState with _$RecommendationProductsState {
  const factory RecommendationProductsState({
    required List<RecommendationData> recommendationProductsList,
    required bool isShimmering,
    required bool isLoading,
    required bool isProductLoading,
    required List<Product> productDetails,
    required List<List<ProductStockModel>> productStockList,
    required int productStockUpdateIndex,
    required int pageNum,
    required bool isLoadMore,
    required bool isBottomOfProducts,
    required bool isSelectSupplier,
    required List<ProductSupplierModel> productSupplierList,
    required int imageIndex,
    required RefreshController refreshController,
    required TextEditingController noteController,
    required int cartCount,
    required bool duringCelebration,
    required bool isCategoryExpand,
    required bool isSearching,
    required TextEditingController searchController,
    required List<SearchModel> searchList,
    required String search,
    required List<Category> productCategoryList,
    required bool isCatVisible,
    required bool isGridView,
    required List<RelatedProductDatum> relatedProductList,
    required bool isRelatedShimmering,
    required int productListIndex,
    required double bottleDeposit,
    required bool isSubUserAddToBasket,
    required bool isIncludedVat,
    required bool isSaleOn,
    required bool isProgress,
    required String language,
    required bool isCartCountChange,
    required int messageCount,
    required String? clubAgentId,
    required bool isGuestUser,
  }) = _RecommendationProductsState;

  factory RecommendationProductsState.initial() => RecommendationProductsState(
        recommendationProductsList: [],
        isShimmering: false,
        isLoading: false,
        isProductLoading: false,
        productDetails: [],
        productStockUpdateIndex: -1,
        productStockList: [
          [const ProductStockModel(productId: '')],
          [],
          []
        ],
        pageNum: 0,
        isLoadMore: false,
        isBottomOfProducts: false,
        isSelectSupplier: false,
        productSupplierList: [],
        imageIndex: 0,
        refreshController: RefreshController(),
        noteController: TextEditingController(),
        cartCount: 0,
        duringCelebration: false,
        isCategoryExpand: false,
        isSearching: false,
        searchController: TextEditingController(),
        searchList: [],
        search: '',
        productCategoryList: [],
        isCatVisible: false,
        isGridView: true,
        relatedProductList: [],
        isRelatedShimmering: false,
        productListIndex: -1,
        bottleDeposit: 0,
        isSubUserAddToBasket: false,
        isIncludedVat: false,
        isSaleOn: false,
        isProgress: false,
        language: AppStrings.hebrewString,
        isCartCountChange: false,
        messageCount: 0,
        clubAgentId: '',
        isGuestUser: false,
      );
}
