part of 'product_sale_bloc.dart';

@freezed
class ProductSaleState with _$ProductSaleState {
  const factory ProductSaleState(
      {required List<ProductSale> productSalesList,
      required String search,
      required List<Product> productDetails,
      required List<List<ProductStockModel>> productStockList,
      required bool isShimmering,
      required bool isLoading,
      required bool isProductLoading,
      required int productStockUpdateIndex,
      required int pageNum,
      required bool isLoadMore,
      required bool isBottomOfProducts,
      required List<ProductSupplierModel> productSupplierList,
      required int imageIndex,
      required RefreshController refreshController,
      required bool isGuestUser,
      required List<RelatedProductDatum> relatedProductList,
      required bool isRelatedShimmering,
      required double bottleDeposit,
      required bool isSubUserAddToBasket,
      required bool isGridView,
      required int productListIndex,
      required bool isIncludedVat,
      required bool isSaleOn,
      required bool isProgress,
      required String language,
      required bool isCartCountChange,
      required int cartCount,
      required int messageCount,
      required String? clubAgentId}) = _ProductSaleState;

  factory ProductSaleState.initial() => ProductSaleState(
      productSalesList: [],
      search: '',
      productDetails: [],
      isShimmering: false,
      isLoading: false,
      isProductLoading: false,
      productStockUpdateIndex: -1,
      productStockList: [
        [const ProductStockModel(productId: '')],
        [],
        []
      ],
      pageNum: 0,
      isLoadMore: false,
      isBottomOfProducts: false,
      productSupplierList: [],
      imageIndex: 0,
      refreshController: RefreshController(),
      isGuestUser: false,
      relatedProductList: [],
      isRelatedShimmering: false,
      bottleDeposit: 0,
      isSubUserAddToBasket: false,
      isGridView: true,
      productListIndex: -1,
      isIncludedVat: false,
      isSaleOn: false,
      isProgress: false,
      language: AppStrings.hebrewString,
      isCartCountChange: false,
      cartCount: 0,
      messageCount: 0,
      clubAgentId: '');
}
