part of 'profile_menu_bloc.dart';

@freezed
class ProfileMenuState with _$ProfileMenuState {
  const factory ProfileMenuState(
      {required String userImageUrl,
      required String userCompanyLogoUrl,
      required String userName,
      required bool isHebrewLanguage,
      required bool isLogOut,
      required bool isLogOutProcess,
      required String language,
      required String applicationVersion,
      required String buildNumber,
      required bool isSubUserUpdateBusinessInfo,
      required bool isSubUserUpdateAdditionalInfo,
      required bool isSubUserUpdateClientFormInfo,
      required bool isSubUserUpdateTimeInfo,
      required bool isSubUserSeeFormsFiles,
      required bool isSubUserCanManageSubUser,
      required bool isSubUserSeeOrder,
      required bool isSubUserSeeReturns,
      required bool isAccountPermissionShimmering,
      required bool isCanSeeInvoices,
      required bool isCanScanDocuments,
      required bool showDocumentScanOnApp,
      required bool isAppOnMaintenance,
      required bool isDialogOpen,
      required bool isIncludedVat,
      required bool isSaleOn,
      required double bottlePrice,
      required bool retryLoading,
      required String? clubAgentId,
      required bool? isAgent,
      required bool? isAgentSwitchToAssignedStore,
      required bool isShimmering,
      required bool isLoading,
      required String customerServicePhone,
      required String customerServiceWhatsApp}) = _ProfileMenuState;

  factory ProfileMenuState.initial() => const ProfileMenuState(
      userImageUrl: '',
      userCompanyLogoUrl: '',
      userName: '',
      isHebrewLanguage: false,
      isLogOut: false,
      isLogOutProcess: false,
      language: AppStrings.hebrewString,
      applicationVersion: "1.0.0",
      buildNumber: '1',
      isSubUserSeeFormsFiles: false,
      isSubUserSeeReturns: false,
      isSubUserUpdateAdditionalInfo: false,
      isSubUserUpdateClientFormInfo: false,
      isSubUserUpdateBusinessInfo: false,
      isSubUserUpdateTimeInfo: false,
      isSubUserCanManageSubUser: false,
      isSubUserSeeOrder: false,
      isAccountPermissionShimmering: false,
      isCanSeeInvoices: false,
      isCanScanDocuments: false,
      showDocumentScanOnApp: false,
      isAppOnMaintenance: false,
      isDialogOpen: false,
      bottlePrice: 0,
      isIncludedVat: false,
      isSaleOn: false,
      retryLoading: false,
      clubAgentId: '',
      isAgent: false,
      isAgentSwitchToAssignedStore: false,
      isShimmering: false,
      isLoading: false,
      customerServicePhone: '',
      customerServiceWhatsApp: '');
}
