part of 'client_form_details_bloc.dart';

@freezed
class ClientFormDetailsState with _$ClientFormDetailsState {
  const factory ClientFormDetailsState(
      {required String agent,
      required List<BusinessType> businessTypeList,
      required String business,
      required TextEditingController owner1NameController,
      required TextEditingController owner1israelIdController,
      required TextEditingController guarantee1NameController,
      required TextEditingController guarantee1idController,
      required TextEditingController guarantee1addressController,
      required TextEditingController guarantee1PhoneController,
      required bool haveMultiple,
      required bool isUpdate,
      required String language,
      required String businessID,
      required String owner,
      required TextEditingController owner2NameController,
      required TextEditingController owner2israelIdController,
      required TextEditingController guarantee2NameController,
      required TextEditingController guarantee2idController,
      required TextEditingController guarantee2addressController,
      required TextEditingController guarantee2PhoneController,
      required TermsConditionReqModel termsConditionReqModel,
      required bool isShimmering,
      required List<String> ownerList,
      required TextEditingController agentCodeController,
      required List<BankDetail> bankList,
      required String bankId,
      required String bankName,
      required TextEditingController accountNumberController,
      required TextEditingController branchController,
      required String filePath,
      required Uint8List pdfPath,
      required bool isOwner2Available,
      required bool isNextEnable,
      required bool isLoading,
      required String owner1Signature,
      required String owner1SignatureLocal,
      required String owner2Signature,
      required String owner2SignatureLocal,
      required String guarantee1Signature,
      required String guarantee1SignatureLocal,
      required String guarantee2Signature,
      required String guarantee2SignatureLocal,
      required bool isGuarantee1Available}) = _ClientFormDetailsState;

  factory ClientFormDetailsState.initial() => ClientFormDetailsState(
      agent: '',
      business: '',
      businessTypeList: [],
      guarantee1addressController: TextEditingController(),
      guarantee1idController: TextEditingController(),
      guarantee1NameController: TextEditingController(),
      guarantee1PhoneController: TextEditingController(),
      businessID: '',
      owner1israelIdController: TextEditingController(),
      owner1NameController: TextEditingController(),
      haveMultiple: false,
      isUpdate: false,
      language: AppStrings.hebrewString,
      owner: '',
      owner2israelIdController: TextEditingController(),
      guarantee2addressController: TextEditingController(),
      guarantee2idController: TextEditingController(),
      guarantee2NameController: TextEditingController(),
      guarantee2PhoneController: TextEditingController(),
      owner2NameController: TextEditingController(),
      termsConditionReqModel: const TermsConditionReqModel(),
      isShimmering: false,
      ownerList: ['1', '2'],
      agentCodeController: TextEditingController(),
      bankList: [],
      bankId: '',
      bankName: '',
      accountNumberController: TextEditingController(),
      branchController: TextEditingController(),
      filePath: '',
      isOwner2Available: false,
      isNextEnable: false,
      pdfPath: Uint8List(1),
      isLoading: false,
      owner1Signature: '',
      owner1SignatureLocal: '',
      owner2Signature: '',
      owner2SignatureLocal: '',
      guarantee1Signature: '',
      guarantee1SignatureLocal: '',
      guarantee2Signature: '',
      guarantee2SignatureLocal: '',
      isGuarantee1Available: false);
}
