part of 'basket_bloc.dart';

@freezed
class BasketState with _$BasketState {
  const factory BasketState(
      {required GetAllCartResModel cartItemList,
      required bool isShimmering,
      required double productWeight,
      required List<ProductDetailsModel> basketProductList,
      required double totalPayment,
      required bool isLoading,
      required bool isSubmitLoading,
      required int productImageIndex,
      required String language,
      required int cartCount,
      required bool isRemoveProcess,
      required double vatPercentage,
      required int supplierCount,
      required double bottleTax,
      required int? bottleQty,
      required List<List<ProductStockModel>> productStockList,
      required int productStockUpdateIndex,
      required bool isCartCountChange,
      required List<Product> productDetails,
      required bool isProductLoading,
      required List<ProductSupplierModel> productSupplierList,
      required bool isQtyUpdated,
      required bool isSelectSupplier,
      required List<RelatedProductDatum> relatedProductList,
      required bool isRelatedShimmering,
      required int productListIndex,
      required bool isAnimation,
      required bool isOrderPending,
      required bool isSubUserAddToBasket,
      required bool isSubUserCanCreateOrder,
      required bool isAccountPermissionShimmering,
      required bool isIncludedVat,
      required bool isSaleOn,
      required bool isPaymentFail,
      required bool isAppOnMaintenance,
      required bool isDialogOpen,
      required bool retryLoading,
      required String bankTransferInfo,
      required bool isAllPaymentAvailable,
      required bool isWalletRelatedError,
      required String errorString,
      required BuildContext? context,
      required List<String> paymentTypesList,
      required String supplierId,
      required bool draftReturnExists,
      required bool updatePaymentMethod,
        required String? clubAgentId,}) = _BasketState;

  factory BasketState.initial() => const BasketState(
        cartItemList: GetAllCartResModel(),
        context: null,
        isShimmering: false,
        productWeight: 0,
        basketProductList: [],
        totalPayment: 0,
        isLoading: false,
        isSubmitLoading: false,
        productImageIndex: 0,
        language: AppStrings.hebrewString,
        cartCount: 0,
        isRemoveProcess: false,
        vatPercentage: 0,
        supplierCount: 1,
        bottleQty: 0,
        bottleTax: 0,
        productStockUpdateIndex: 0,
        productStockList: [
          [ProductStockModel(productId: '')],
          []
        ],
        isCartCountChange: false,
        paymentTypesList: [],
        productDetails: [],
        isProductLoading: false,
        isWalletRelatedError: false,
        productSupplierList: [],
        isQtyUpdated: false,
        isSelectSupplier: false,
        relatedProductList: [],
        isRelatedShimmering: false,
        bankTransferInfo: '',
        productListIndex: -1,
        isAnimation: false,
        isOrderPending: false,
        isSubUserAddToBasket: false,
        isSubUserCanCreateOrder: false,
        isAccountPermissionShimmering: false,
        isIncludedVat: false,
        isSaleOn: false,
        isAppOnMaintenance: false,
        isDialogOpen: false,
        retryLoading: false,
        isPaymentFail: true,
        isAllPaymentAvailable: false,
        errorString: '',
        supplierId: '',
        draftReturnExists: false,
        updatePaymentMethod: false,
    clubAgentId : '',
      );
}
